<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPgzHabb\Eccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPgzHabb/Eccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPgzHabb.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPgzHabb\Eccube_KernelProdContainer::class, Eccube_KernelProdContainer::class, false);
}

return new \ContainerPgzHabb\Eccube_KernelProdContainer([
    'container.build_hash' => 'PgzHabb',
    'container.build_id' => '07644d01',
    'container.build_time' => 1681530044,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPgzHabb');
